# config/settings.yaml
---
raw_data_paths:
  daily:   "../data/raw/CBS_2021-2023_Daily_Weather.csv"
  hourly:  "../data/raw/CBS_2021-2023_Hourly_Weather.csv"
  full:    "../data/raw/CBS_2021-2023_Full.csv"

processed_data_paths:
  daily:   "../data/processed/daily_data.parquet"
  hourly:  "../data/processed/hourly_data.parquet"
  # rides:        "../data/processed/rides.parquet"
  # rides:        "../data/processed/rides.parquet"
  # rides:        "../data/processed/rides.parquet"